<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MitraLaundrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('mitra_laundry')->insert([
            [
                'id' => 1,
                'nama_mitra' => 'KosanFresh Laundry',
                'foto_toko' => 'uploads/mitra_1.png',
                'latitude' => -8.58260000,
                'longitude' => 116.10750000,
                'alamat' => 'Jl. Pejanggik No. 12, Mataram (Pusat Kota)',
                'no_telp' => '081234567890',
                'rating' => 4.9,
                'harga_per_kg' => 7000,
                'jam_buka' => 'Open until 21:00',
                'status_buka' => 1,
                'icon_type' => 'kiloan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'nama_mitra' => 'Express Shine',
                'foto_toko' => 'uploads/mitra_2.png',
                'latitude' => -8.59020000,
                'longitude' => 116.11540000,
                'alamat' => 'Jl. Panca Usaha No. 45, Cilinaya, Mataram',
                'no_telp' => '081234567891',
                'rating' => 4.7,
                'harga_per_kg' => 9500,
                'jam_buka' => 'Open 24 Hours',
                'status_buka' => 1,
                'icon_type' => 'express',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'nama_mitra' => 'Sahabat Kos Laundry',
                'foto_toko' => 'uploads/mitra_1.png',
                'latitude' => -8.58300000,
                'longitude' => 116.09500000,
                'alamat' => 'Jl. Airlangga No. 8, Mataram',
                'no_telp' => '081234567892',
                'rating' => 4.5,
                'harga_per_kg' => 6000,
                'jam_buka' => 'Open until 20:00',
                'status_buka' => 1,
                'icon_type' => 'kiloan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'nama_mitra' => 'EcoWash Pure',
                'foto_toko' => 'uploads/mitra_2.png',
                'latitude' => -8.60150000,
                'longitude' => 116.11300000,
                'alamat' => 'Jl. Bung Karno, Pagutan, Mataram',
                'no_telp' => '081234567893',
                'rating' => 4.8,
                'harga_per_kg' => 8500,
                'jam_buka' => 'Open until 22:00',
                'status_buka' => 1,
                'icon_type' => 'eco',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'nama_mitra' => 'FreshClean Laundry',
                'foto_toko' => 'uploads/mitra_1.png',
                'latitude' => -8.56200000,
                'longitude' => 116.07700000,
                'alamat' => 'Jl. Saleh Sungkar, Ampenan, Mataram',
                'no_telp' => '081234567894',
                'rating' => 4.6,
                'harga_per_kg' => 7500,
                'jam_buka' => 'Open until 21:30',
                'status_buka' => 1,
                'icon_type' => 'satuan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'nama_mitra' => 'WashTra Laundry Ekspress',
                'foto_toko' => 'uploads/mitra_washtra.png',
                'latitude' => -8.59059420,
                'longitude' => 116.09259180,
                'alamat' => 'Jl. Majapahit No.88C, Kekalik Jaya, Kec. Sekarbela, Kota Mataram, Nusa Tenggara Bar. 83127',
                'no_telp' => '082341961954',
                'rating' => 4.8,
                'harga_per_kg' => 15000,
                'jam_buka' => 'Senin - Minggu 07:00 - 22:00',
                'status_buka' => 1,
                'icon_type' => 'express',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'nama_mitra' => 'LAUNDRY LOMBOK',
                'foto_toko' => 'uploads/laundry_lombok.png',
                'latitude' => -8.59210790,
                'longitude' => 116.08926740,
                'alamat' => 'Jl. Swasembada No.26, Kekalik Jaya, Kec. Sekarbela, Kota Mataram',
                'no_telp' => '085941306413',
                'rating' => 5.0,
                'harga_per_kg' => 7000,
                'jam_buka' => 'Senin - Minggu 07:00 - 21:00',
                'status_buka' => 1,
                'icon_type' => 'kiloan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'nama_mitra' => 'MAULaundry Mataram',
                'foto_toko' => 'uploads/mitra_maulaundry_storefront.png',
                'latitude' => -8.59282220,
                'longitude' => 116.08937300,
                'alamat' => 'Jl. Swasembada No.37, Kekalik Jaya, Kec. Sekarbela, Kota Mataram',
                'no_telp' => '087736861615',
                'rating' => 4.8,
                'harga_per_kg' => 25000,
                'jam_buka' => 'Senin - Minggu 08:00 - 22:00',
                'status_buka' => 1,
                'icon_type' => 'express',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'nama_mitra' => 'Mate Shoes Care',
                'foto_toko' => 'uploads/mitra_mate_shoes_care.png',
                'latitude' => -8.58840500,
                'longitude' => 116.08540920,
                'alamat' => 'Jl. Swakarya Raya, Kekalik Jaya, Kec. Sekarbela, Kota Mataram. dekat Kudeta Barbershop Kekalik',
                'no_telp' => '087898824993',
                'rating' => 5.0,
                'harga_per_kg' => 25000,
                'jam_buka' => 'Senin - Minggu 09:00 - 21:00',
                'status_buka' => 1,
                'icon_type' => 'sepatu',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
